########################################
# CONSTANTS
########################################
string PLAY = "play"                    #Motion Play Start
string PAUSE = "pause"                  #Pause motion
string CLEAR = "clear"                  #Saved Motion All Clear
string STOP = "stop"                    #Stop motion after playing this motion
string CANCEL_STOP = "cancel_stop"      #Cancel Stop motion request
string BREAK = "break"                  #Play next motion after playing this motion
string CANCEL_BREAK = "cancel_break"    #Cancel to break request
string RETURN_FIRST = "return_first"    #Return to first pose in first motion
string RETURN_MOTION = "return_motion"  #Return to first pose in this motion
string E_STOP = "e_stop"                #Immediate stop motion

########################################
# Messages
########################################
string request
